name = "refinery"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Refinery"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = true

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "discretion"
scope = "imbrem"

[[lean_lib]]
name = "Refinery"
