import Refinery.Ty
import Refinery.Term
import Refinery.Term.Extrinsic.Semantics.Typing
import Refinery.Term.Extrinsic.Subst
import Refinery.Term.Extrinsic.Semantics.Wk
import Refinery.Term.Extrinsic.Semantics.Minimal
import Refinery.Term.Extrinsic.Refinement.Uniform
import Refinery.Term.Extrinsic.Refinement.Semantics.Uniform
import Refinery.Ctx.Semantics.Coherence
